application: mikan767676
#application: stg-mikan767676
version: 1
runtime: python
api_version: 1
#threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /tinymce
  static_dir: tinymce  
  
- url: /static
  static_dir: static

## 一時的にコメントアウト
#- url: /rpc|/xmlrpc\.php|/rpc/.*
#  script: api_rpc.py
#  
#- url: /themes/.*
#  script: theme_files.py

## 要らない記述
#- url: /myadmin/.*|/myadmin
#  script: $PYTHON_LIB/google/appengine/ext/admin
#  login: admin
#
#- url: /admin/post|/admin/entries/(post|page)|/admin/links|/admin/categories|/admin/comments
#  script: admin.py
#  login: required
#
#- url: /admin/{0,1}
#  script: admin.py
#  login: required
#
#- url: /admin/link|/admin/category|/admin/(post|page)|/admin/lang|/admin/filemanager|/admin/upload|/admin/uploadex
#  script: admin.py
#  login: required
#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin
#
#- url: /tinymce/.*
#  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /admin/.*
  script: admin.py
  login: required

- url: /.*
  script: blog.py
#  script: blog.app

builtins: 
- appstats: on
- remote_api: on

#libraries:
#- name: django
#  version: latest
#- name: webapp2
#  version: latest
#- name: markupsafe                                                              
#  version: latest 
#- name: PIL
#  version: latest
#- name: pycrypto
#  version: latest
#- name: jinja2                                                                  
#  version: latest 